# ─────────────────────────────────────────────────────────────────────────────
# modules/storage/main.tf
# MED-118: Provision Azure Blob Storage & Configure Lifecycle Policies
#
# What this creates:
#   1. Storage Account      — the top-level container for all blobs
#   2. medlink-documents    — stores patient documents with soft-delete
#   3. medlink-pdfs         — stores generated PDFs with soft-delete
#   4. medlink-tfstate      — stores Terraform remote state with versioning
#   5. Lifecycle Policy     — tiers documents/pdfs to Cool then Archive
# ─────────────────────────────────────────────────────────────────────────────

locals {
  common_tags = {
    # Functional tags
    env        = var.environment
    app        = var.project
    region     = var.region
    managed_by = "terraform"
    module     = "storage"
    # Accounting tags
    costcenter = var.cost_center
    # Ownership tags
    opsteam      = var.owner
    businessunit = var.business_unit
    # Classification tags
    criticality = var.criticality
  }
}


# ─────────────────────────────────────────────────────────────────────────────
# STORAGE ACCOUNT
# The parent resource that holds all containers and blobs.
# Think of it like a hard drive — containers are folders inside it.
#
# Key settings:
# - Standard LRS: 3 copies of data in the same Azure region. Cheap and
#   sufficient for dev. Use GRS (geo-redundant) for prod.
# - min_tls_version TLS1_2: enforces encrypted connections only.
# - allow_blob_public_access false: no container or blob can ever be
#   made public — all access requires authentication.
# - https_traffic_only_enabled: blocks plain HTTP connections entirely.
# ─────────────────────────────────────────────────────────────────────────────

resource "azurerm_storage_account" "main" {
  name                     = var.storage_account_name
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_kind             = "BlobStorage"
  account_tier             = var.account_tier
  account_replication_type = var.account_replication_type
  access_tier              = "Hot"


  # Security hardening
  min_tls_version                 = "TLS1_2"
  allow_nested_items_to_be_public = false
  enable_https_traffic_only       = true
  shared_access_key_enabled       = false
  default_to_oauth_authentication = true

  # Blob service properties — soft delete and versioning are configured
  # at the storage account level and then referenced per container.
  blob_properties {
    # Soft delete for blobs — deleted blobs are recoverable for 7 days.
    # This protects against accidental deletion of patient documents.
    delete_retention_policy {
      days = var.soft_delete_retention_days
    }

    # Soft delete for containers — if an entire container is deleted
    # accidentally, it can be recovered within 7 days.
    container_delete_retention_policy {
      days = var.soft_delete_retention_days
    }

    # Versioning keeps a full history of every blob change.
    # Required for the tfstate container so state file history is preserved.
    versioning_enabled = true
  }

  tags = local.common_tags
}

# ─────────────────────────────────────────────────────────────────────────────
# CONTAINERS
# Containers are like folders inside the storage account.
# container_access_type = "private" means no public internet access.
# All reads and writes require an authenticated request.
# ─────────────────────────────────────────────────────────────────────────────

# Container 1 — Patient documents
# Stores uploaded documents (referrals, lab results, consent forms).
# Soft-delete is inherited from the storage account blob_properties above.
resource "azurerm_storage_container" "documents" {
  name                  = "medlink-documents"
  storage_account_name  = azurerm_storage_account.main.name
  container_access_type = "private"
}

# Container 2 — Generated PDFs
# Stores PDFs generated by the platform (prescriptions, reports, invoices).
# Soft-delete is inherited from the storage account blob_properties above.
resource "azurerm_storage_container" "pdfs" {
  name                  = "medlink-pdfs"
  storage_account_name  = azurerm_storage_account.main.name
  container_access_type = "private"
}

# Container 3 — Terraform remote state
# Stores the Terraform state file for this infrastructure.
# Versioning is critical here — if state gets corrupted, you can restore
# a previous version. Versioning is enabled at the account level above.
resource "azurerm_storage_container" "tfstate" {
  name                  = "medlink-tfstate"
  storage_account_name  = azurerm_storage_account.main.name
  container_access_type = "private"
}

# ─────────────────────────────────────────────────────────────────────────────
# LIFECYCLE MANAGEMENT POLICY
# Automatically moves blobs between storage tiers based on age.
# This saves cost significantly over time:
#
# Hot tier   (default) — fastest access, most expensive
# Cool tier  (90 days) — slower access, ~50% cheaper than Hot
# Archive tier (365 days) — hours to retrieve, ~90% cheaper than Hot
#
# Applied to documents and pdfs containers only.
# The tfstate container is excluded — state files must stay in Hot tier
# for instant access during terraform operations.
# ─────────────────────────────────────────────────────────────────────────────

resource "azurerm_storage_management_policy" "lifecycle" {
  storage_account_id = azurerm_storage_account.main.id

  rule {
    name    = "documents-lifecycle"
    enabled = true

    filters {
      # Apply this rule only to blobs inside the documents container.
      prefix_match = ["medlink-documents/"]
      blob_types   = ["blockBlob"]
    }

    actions {
      base_blob {
        # Move to Cool tier after 90 days of no access.
        # Patient documents older than 90 days are rarely accessed —
        # Cool tier saves ~50% cost with acceptable retrieval speed.
        tier_to_cool_after_days_since_modification_greater_than = var.cool_tier_after_days

        # Move to Archive tier after 365 days.
        # Documents older than a year are kept for compliance but
        # almost never accessed — Archive saves ~90% cost.
        tier_to_archive_after_days_since_modification_greater_than = var.archive_tier_after_days
      }

      # Apply the same tiering to soft-deleted blobs.
      # This prevents deleted documents from staying in expensive Hot tier
      # during their 7-day recovery window.
      snapshot {
        tier_to_cold_after_days_since_creation_greater_than = var.cool_tier_after_days
      }
    }
  }

  rule {
    name    = "pdfs-lifecycle"
    enabled = true

    filters {
      # Apply this rule only to blobs inside the pdfs container.
      prefix_match = ["medlink-pdfs/"]
      blob_types   = ["blockBlob"]
    }

    actions {
      base_blob {
        tier_to_cool_after_days_since_modification_greater_than    = var.cool_tier_after_days
        tier_to_archive_after_days_since_modification_greater_than = var.archive_tier_after_days
      }

      snapshot {
        tier_to_cold_after_days_since_creation_greater_than = var.cool_tier_after_days
      }
    }
  }
}
